// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osfsgfjcqqyxrwlcvbov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZnNnZmpjcXF5eHJ3bGN2Ym92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMzc4OTgsImV4cCI6MjA2NDgxMzg5OH0.ADMgQxwNbKforXGNshno7_z1noxCdheNvHAMjpbjejk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);